### ISSUE TITLE
Line spaces are removed

### ISSUE THREAD

**Issue by amk221** [ember-tooling/prettier-for-handlebars-vscode#15]
I'm moving from Atom to VSCode

Atom with Prettier for Handlebars would convert this:

```handlebars
<h1>
  Title
</h1>


<p>
  Lorem Ipsum
</p>
```

to this:

```handlebars
<h1>
  Title
</h1>

<p>
  Lorem Ipsum
</p>
```

Whereas, with VSCode Prettier for Handlebars would convert it to this:

```handlebars
<h1>
  Title
</h1>
<p>
  Lorem Ipsum
</p>
```

I'm not sure who is wrong here, but I certainly prefer the spacing to remain.

Thoughts?

**Comment by mupkoo** [comment]
I just installed the extension and get the same result. It looks like the Prettier playground produces the desired result

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFgRgHwB0oAEBAKgJYwA2c+qA9FnlPjQA6NEAyEATnALYEAkiwDOAVz41abEABoQEFjFLQRyUAENu3CAHcACloRqUGiro0BPNfIBG3DWADWcGAGUWj0lADmyGNxicPL8tnAAJuERHBq+Yho+cABiPHwaMMq+yCAaYjAQciDoMHwUAOro5HAinmBwbsbkpABu5JbZYCI2IN4icNww+g4+acgAZmZ98gBWIgAeAEIOzq5uGnxwHN5w45PBILNzbt4+VACKYhDwuxRTIJ7cfdzZp6R8G8-yLNzeMGWk4Rg6GQAA4AAxfHR9MoOFjZb7VfrNHbyACOl3gQ0UJhyIgAtFA4BEIoVeOjSLwhglRkgJrd9n0+KR-IEGSdzhidrS9vIYBpbP9AcCkAAmXkOUgUE4AYQg7w02WqAFZCmI+sR+SY6XdmkFBFAorA3GAfkoAIIGtwwSxUG59AC+9qAA

**Comment by locks** [comment]
Closing as documented in the README examples. Could it be because this extension pins prettier to a certain version number?
