### ISSUE TITLE
Error: Handlebars partials are not supported

### ISSUE THREAD

**Issue by CiriousJoker** [ember-tooling/prettier-for-handlebars-vscode#16]
Not much to add here, I can provide stacktrace if you want

**Comment by Alonski** [comment]
@CiriousJoker The issue is probably upstream in the Prettier `glimmer` parser.

Can you explain what you are trying to do and what errors you get?

Also since partials are deprecated this probably won't ever be fixed anyways :)

**Comment by CiriousJoker** [comment]
Didn't know that partials are deprecated
