### ISSUE TITLE
All the code is deleted when formatting.

### ISSUE THREAD

**Issue by justanindieguy** [ember-tooling/prettier-for-handlebars-vscode#19]
Whenever I format all the code is deleted and I end up with a blank document.

**Comment by Alonski** [comment]
@justanindieguy Can you please share an example project?

**Comment by ardittristan** [comment]
I am able to reproduce, it only happens if the document starts with `<!DOCTYPE html>` for me

**Comment by playitcool** [comment]
Can confirm what @ardittristan is saying- if the document starts w/ `<!DOCTYPE html>`, the extension has issues. For me, it just wouldn't format any of the template. Once removed, it worked as expected

**Comment by Alonski** [comment]
@playitcool Does it happen when running Prettier from the command line?

**Comment by playitcool** [comment]
@Alonski - yep 
![image](https://user-images.githubusercontent.com/947187/107561071-f2553600-6b92-11eb-8765-554ab8aa002a.png)

**Comment by Alonski** [comment]
Ok so it's a bug in Prettier itself. Can you update Prettier to latest and see if it still breaks please? @playitcool

**Comment by playitcool** [comment]
@Alonski  - will do! I just came to the same conclusion. Appreciate your time.

**Comment by locks** [comment]
This extension is deprecated, so please use Prettier directly!
