### ISSUE TITLE
Removes the backslash symbol used when escaping handlebars expressions

### ISSUE THREAD

**Issue by cryarchy** [ember-tooling/prettier-for-handlebars-vscode#20]
Removes the backslash symbol used when [escaping handlebars expressions](https://handlebarsjs.com/guide/expressions.html#escaping-handlebars-expressions)

For example `\{{escaped}}` becomes `{{escaped}}`

It also reformats raw blocks breaking them.

For example:

```
{{{{raw}}}}
  {{escaped}}
{{{{/raw}}}}
```
becomes:

```
{{#raw}}
  {{escaped}}
{{/raw}}
```

**Comment by locks** [comment]
This extension is deprecated, so please use Prettier directly!
