### ISSUE TITLE
Incorrectly formats glimmer array syntax

### ISSUE THREAD

**Issue by fpauser** [ember-tooling/prettier-for-handlebars-vscode#22]
This
```hbs
{{#with action.params.[0] as |param|}}
  <span>{{param.label}}</span>
{{/with}}
```
gets formatted as
```hbs
{{#with action.params.0 as |param|}}
  <span>
    {{param.label}}
  </span>
{{/with}}
```

which is wrong and triggers a parse error. See [Prettier Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuExgGIDuBLGALAAgEMwZtoA6AByICciBbAZwoG0AGAXWKYIB8a9BnwC+IgDpQCBADxMaUAHxpBjCgBsiAIzjqxMgPTyiSyWgM58YkABoQEKmWhNkoOrQiYACnQQuUROqYRACeLnZa9GAA1nAwAMo0YNhQAObIMLQArnB2cAw6ACaFcIUAMiapWUSpcABiELQMRDBkacggRFkwELYgeDAM6gDqeLhwxmBw8X642ABuuCEdYEzhIClMcLQwXvSpzcgAZoFbdgBWTAAeAEJRsQmMcGUpcMenuSCXV-EpqepwACKWQg8He6jOIEEW1oHX+2AYDG2fSotBSMGG2EK+GQAA52HZURAtsN6FQOqiJtt5m87ABHEHwPYOfydJgAWigcFKpT6tDgDOw-L2NUOSBOEM+WwY2Ay2SlfwBwNBb3FHzsMG0mOxeGQACYNfRsOo-gBhCCIogdCYAVj6WS2ABVtP4JZD5jkAJJQEqweJgNGOACCPviMBCAPBWzEQA).

Any idea how to work around this?

**Comment by fpauser** [comment]
Ok, the workaround for now seems to be:

```hbs
{{#with (get action.params "0") as |param|}}
  <span>{{param.label}}</span>
{{/with}}
```

**Comment by locks** [comment]
This extension is deprecated, so please use Prettier directly!
