### ISSUE TITLE
Update to ^2.3.0

### ISSUE THREAD

**Issue by betocantu93** [ember-tooling/prettier-for-handlebars-vscode#23]
Hello, 👋🏼 

With [v2.3.0](https://prettier.io/blog/2021/05/09/2.3.0.html#move-handlebars-support-out-of-alpha-to-release-10290httpsgithubcomprettierprettierpull10290-by-dcyrillerhttpsgithubcomdcyriller--thorn0httpsgithubcomthorn0) prettier for handlebars official release, I was wondering if we could update the prettier dependency?

Thanks

**Comment by betocantu93** [comment]
Or maybe we can just use Prettier - Code formatter directly? 🤔

**Comment by locks** [comment]
This extension is deprecated, so please use Prettier directly!
